Repository BBack-BBoo-Team/Sebadog-book-server, pull requests merged in 2024-01, with the labels that each got.

#6 [env] 초기 패키지 구조 구축 #5
  src/main/java/com/book/app/SebadogApp.java
  src/main/java/com/book/app/infra/config/README.md
  src/main/java/com/book/app/modules/account/README.md
  src/main/java/com/book/app/modules/books/README.md
  src/main/java/com/book/app/modules/global/README.md
  src/test/java/com/book/app/SebadogBookServerApplicationTests.java
Labels: env

#9 [서버] 도서 등록 개발
  build.gradle
  src/main/java/com/book/app/SebadogApp.java
  src/main/java/com/book/app/modules/books/README.md
  src/main/java/com/book/app/modules/books/controller/BookController.java
  src/main/java/com/book/app/modules/books/dto/BookRequestDto.java
  src/main/java/com/book/app/modules/books/dto/BookResponseDto.java
  src/main/java/com/book/app/modules/books/entity/Book.java
  src/main/java/com/book/app/modules/books/repository/BookRepository.java
  src/main/java/com/book/app/modules/books/service/BookService.java
  src/main/java/com/book/app/modules/books/service/impl/BookServiceImpl.java
  src/main/java/com/book/app/modules/global/entity/BaseTimeEntity.java
  src/test/java/com/book/app/modules/books/BookControllerTest.java
Labels: enhancement

#10 [서버] 사용자 정보 조회 및 저장 API
  build.gradle
  src/main/java/com/book/app/infra/config/JpaConfig.java
  src/main/java/com/book/app/modules/account/Account.java
  src/main/java/com/book/app/modules/account/AccountController.java
  src/main/java/com/book/app/modules/account/AccountRepository.java
  src/main/java/com/book/app/modules/account/dto/AccountInfoDto.java
  src/main/java/com/book/app/modules/account/dto/SignUpDto.java
  src/main/java/com/book/app/modules/account/service/AccountService.java
  src/main/java/com/book/app/modules/account/service/AccountServiceImpl.java
  src/main/java/com/book/app/modules/global/response/SuccessResponseDto.java
  src/test/java/com/book/app/SebadogBookServerApplicationTests.java
  src/test/java/com/book/app/infra/MockMvcTest.java
  src/test/java/com/book/app/modules/account/AccountControllerTest.java
Labels: enhancement

#14 [서버] Compile 오류 수정
  src/main/java/com/book/app/SebadogApp.java
  src/main/java/com/book/app/modules/books/entity/Book.java
  src/main/java/com/book/app/modules/global/entity/BaseTimeEntity.java
Labels: bug
